### ISSUE TITLE
RadioButton works like a checkbox in RadioGroup

### ISSUE THREAD

**Issue by zishanj** [PolymerElements/paper-radio-group#13]
I am having issue with `PaperRadioButtons` when using inside `PaperRadioGroup`. They are acting more like a checkbox than RadioButton. Also when I use PaperRadioButton without PaperRadioGroup, they still acts like a checkbox. What's the idea behind making RadioButton acting like a checkbox with states `selected` and `unselected`?

**Comment by notwaldorf** [comment]
The idea was that if outside a `paper-radio-group`, a `paper-checkbox` and a `paper-radio-button` are basically the same element, without different styles. The fact that it doesn't work correctly inside the `paper-radio-group` is a bug, and I am fixing it in https://github.com/PolymerElements/paper-radio-group/pull/9  :)

**Comment by zishanj** [comment]
Ok... Looking forward for it's fix.
