### ISSUE TITLE
doc examples in element catalog are outdated

### ISSUE THREAD

**Issue by m4b** [PolymerElements/paper-radio-group#15]
Looks like [the docs are](https://elements.polymer-project.org/elements/paper-radio-group) out of date for `<paper-radio-group>` example, e.g.:

````html
<paper-radio-group selected="small">
  <paper-radio-button name="small" label="Small"></paper-radio-button>
  <paper-radio-button name="medium" label="Medium"></paper-radio-button>
  <paper-radio-button name="large" label="Large"></paper-radio-button>
</paper-radio-group>
````

Setting label doesn't seem to do anything, and demos set the label by putting text in the tag, i.e.:

````
<paper-radio-button>Label<paper-radio-button>
````

**Comment by notwaldorf** [comment]
This was fixed in https://github.com/PolymerElements/paper-radio-group/pull/17, and should make it to the catalog in its next release.
