### ISSUE TITLE
listen to changes in <content>

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/paper-radio-group#30]
D label get stuck in hidden mode

```html
 <iron-localstorage name="club" value="{{ttt}}"></iron-localstorage>
<iron-localstorage name="option" value="{{option}}"></iron-localstorage>
                <paper-radio-group class="vertical layout" selected="{{option}}">
                    <paper-radio-button name="A">test1</paper-radio-button>
                    <paper-radio-button name="B">test2</paper-radio-button>
                    <paper-radio-button name="C">test3</paper-radio-button>
                    <paper-radio-button name="D">[[ttt]]</paper-radio-button>
                </paper-radio-group>
```
example http://gcl-12.appspot.com

click on the empty radio space first to select something to put it in localstorage then refresh the page.

![image](https://cloud.githubusercontent.com/assets/863731/9563794/11899c08-4e90-11e5-9eba-009f2c9d0443.png)

**Comment by arthurevans** [comment]
@notwaldorf I think this is an issue with `paper-radio-button`'s handling of `textContent`. It seems like the component needs to re-evaluate the label when textContent changes, not just on attached:

https://github.com/PolymerElements/paper-radio-button/blob/master/paper-radio-button.html#L112

**Comment by arthurevans** [comment]
(In Slack) @gertcuykens said he was on v1.0.6.

**Comment by notwaldorf** [comment]
@arthurevans Yup, we're waiting on a Polymer change upstream that will let you listen to changes in `<content>`, which isn't possible right now.

**Comment by gertcuykens** [comment]
do we have a estimate how long it wil take? or how long they have been working on it already :)

**Comment by notwaldorf** [comment]
Pretty soon, actually! It's in the testing phase, so maybe 2 weeks? It's at the top of the stack, it just keeps getting pushed by slightly-more-important bugs.

Though, in the meantime: does this patch work for you? https://github.com/PolymerElements/paper-radio-button/pull/49
I suspect you don't actually need the whole listener to work right now, but just the fix in that patch.

**Comment by arthurevans** [comment]
I wonder if there is a use case for labeling your radio buttons with icons only? In this case, hiding the label when textContent is empty would prevent you from doing that.

**Comment by notwaldorf** [comment]
@arthurevans I've tagged a new release where we no longer hide the label at all, since that really doesn't work until listening to `<content>` works.

@gertcuykens would you mind pulling the new version of `paper-radio-button` and see if it fixes your issue, please?

**Comment by arthurevans** [comment]
So I Tried This at Home :tm: and it worked great, both with icons and with data-bound values.

![radio-icons](https://cloud.githubusercontent.com/assets/1149422/9614562/561cc840-50a7-11e5-9534-ee5a927c3780.png)

:clap::clap: :tada:

**Comment by notwaldorf** [comment]
Super! Little victories! Closing as fixed :)

**Comment by gertcuykens** [comment]
http://gcl-12.appspot.com/ yep 1.0.7 working for me to now :)

![image](https://cloud.githubusercontent.com/assets/863731/9621242/730ad136-5124-11e5-8f51-d20bd5282e59.png)

Ps how do you pull PolymerElements/paper-radio-button#49 if it is not in master yet ?
Could it be bucket-o-fixes is something private I can't access?

**Comment by notwaldorf** [comment]
Oh, it's merged in master now, but normally you'd have to check out the branch locally (i think `git checkout pr/49 is the magical incantation) and run it from there
