### ISSUE TITLE
paper-radio-button behaves like checkbox when using dom-repeat

### ISSUE THREAD

**Issue by MartonEstok** [PolymerElements/paper-radio-group#31]
inside a paper-radio-group I've put a dom-repeat template to display a couple of paper-radio-buttons. They behave as they were checkboxes, not deselecting the first selection after the second is made.

This works as expected (from docs):

```HTML
<paper-radio-group >
  <paper-radio-button name="small">Small</paper-radio-button>
  <paper-radio-button name="medium">Medium</paper-radio-button>
  <paper-radio-button name="large">Large</paper-radio-button>
</paper-radio-group>
```

This does not:
```HTML
<paper-radio-group>
    <template is="dom-repeat" id="instanceList" items="{{instanceData}}">
        <paper-radio-button>{{item.INSTANCE_NAME}}</paper-radio-button>
    </template>
</paper-radio-group>
```

**Comment by notwaldorf** [comment]
The `paper-radio-button`s in the second example don't have a `name` attribute, which makes them "different" from the `paper-radio-group`'s perspective.

If you add names to them (like in the first example), it should work as expected.

**Comment by MartonEstok** [comment]
This is perfect, I apologize for the false alarm! :)

**Comment by notwaldorf** [comment]
@MartonEstok No worries! Easy fix :)
