### ISSUE TITLE
dom-module declaration uses 'name' instead of 'id'

### ISSUE THREAD

**Issue by ThatJoeMoore** [PolymerElements/paper-radio-group#35]
The dom-module declaration should use id for the element name (per https://www.polymer-project.org/1.0/docs/devguide/local-dom.html#template-stamping).

Current: 
<dom-module name="paper-radio-group">

Expected:
<dom-module id="paper-radio-group">

Because of this, Polymer 1.1.3 does not load paper-radio-group properly.

Pull request is coming soon.

**Comment by notwaldorf** [comment]
Fixed in https://github.com/PolymerElements/paper-radio-group/pull/36
