### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by jakemac53** [PolymerElements/paper-radio-group#46]
Looks like a bunch of the tests are failing on travis https://travis-ci.org/PolymerElements/paper-radio-group/jobs/88467377

**Comment by notwaldorf** [comment]
@jakemac53 Yeah, I think there's breakage in `iron-selector` that should be fixed soon /cc @cdata

**Comment by jakemac53** [comment]
Fwiw, at least some of these tests can be fixed by wrapping the expects in a call to `async`. It looks like the dom is just getting updated async when it used to be sync?

**Comment by notwaldorf** [comment]
Fixed in #47
