### ISSUE TITLE
Padding of the radio buttons is fixed 

### ISSUE THREAD

**Issue by IntranetFactory** [PolymerElements/paper-radio-group#55]
The padding of the radio buttons is currently fixed (https://github.com/PolymerElements/paper-radio-group/blob/master/paper-radio-group.html#L60).

I think it a var or mixin should be used, so that the space between the buttons can be changed.

**Comment by notwaldorf** [comment]
Thanks for filing this! Are you interested in sending a PR adding a custom property to control this? Maybe something like `--paper-radio-group-item-padding` or something? 🎈
