### ISSUE TITLE
Radio groups don't play well with iron-form

### ISSUE THREAD

**Issue by sgammon** [PolymerElements/paper-radio-group#66]
### Description

Radio groups are essentially enumerations. As form UI, they generally allow only one selection, and optionally allow empty selection. `<paper-radio-group>` accomplishes this well.

Forms are sets of fields, sometimes containing radio groups. `<iron-form>` is a great tool for grouping such fields, and `<paper-radio-group>` should play nicely with it.
### Expected outcome

Placing a `<paper-radio-group>` inside an `<iron-form>` should mean that:
- Calling `serialize()` on the enclosing form includes any value from `<paper-radio-group>`, equivalent to `<paper-radio-group>.selected`
- Calling `validate()` on the enclosing form returns false, when there is no selection and `allowEmptySelection` is not set to `true`
### Actual outcome

Nothing, the element is not noticed at all. If subelements (i.e. `<paper-radio-button>`) have a `name` attribute (which is, as #58 points out, ironically the default value of `attrForSelected`), they are included in the `serialize()` payload with a value of `"on"`, but this does not express the enumerative nature of a `<paper-radio-group>`.
### Steps to reproduce
1. Put a `iron-form` element in the page.
2. Put a `paper-radio-group` element inside that form, with a few valid `paper-radio-button`(s).
3. Make sure the `paper-radio-group` has a `name`.
4. Open the page in a web browser.
5. Make a selection in the `paper-radio-group`.
6. Fire up your trusty inspector and run `serialize()` on your `iron-form`. Note that no value is produced.
### Browsers Affected

Well, all of them, because there is no code to do it.

**Comment by notwaldorf** [comment]
There was a long discussion in https://github.com/PolymerElements/paper-radio-group/issues/32 about why I thought this wasn't a great idea :(

**Comment by sgammon** [comment]
Understood. That's really solid logic, @notwaldorf. Is there perhaps a middle ground we could find, though? It's hard as it is to represent an enum structure properly in JSON, and this `paper-radio-group` change would make that use case much easier.

I don't mean to be disruptive, but what if this could be considered a flaw in the spec? I wouldn't advocate anymore for this to be *default* functionality, because you're right, it should be consistent. But perhaps a `Boolean` flag to opt-in could be considered, in the same way that some other components do (i.e. `iron-ajax` and its awesome [jsonPrefix](https://elements.polymer-project.org/elements/iron-ajax#property-jsonPrefix) feature, which is very useful, but non-spec).

Please let me know if I am off-base :) love Polymer and just want to see it get better!
