### ISSUE TITLE
Nested radio groups incorrect behavior

### ISSUE THREAD

**Issue by codekrolik** [PolymerElements/paper-radio-group#73]
### Description
Nested radio groups behave incorrectly.
Selecting a parent item affects selection of nested radio groups.

### Expected outcome

When parent radio-group selects an item, only parent item should get selected and nothing else.
When nested radio-group selects an item, only item in nested radio-group is getting selected and nothing else.

### Actual outcome

When parent selects an item, nested radio group also selects items, whether you want it or not.

### Live Demo

https://jsbin.com/kiwoqunice/edit?html,css,js,output

### Steps to reproduce

1. Open https://jsbin.com/kiwoqunice/edit?html,css,js,output
2. Select parent item #2 (Remove all links)
3. Nested radio-group items will get erroneously selected

### Browsers Affected

- [x] Chrome

**Comment by notwaldorf** [comment]
Nested radio groups are not supported at the moment, since the underlying `iron-selector` element does not support it. This is the tracking issue for that feature: https://github.com/PolymerElements/iron-selector/issues/42
