### ISSUE TITLE
paper-radio-group is multiselectable even though multi is not set to true

### ISSUE THREAD

**Issue by Nachtmerrie** [PolymerElements/paper-radio-group#74]
### Description
paper-radio-group is multiselectable even though multi is not set to true
### Expected outcome

Only able to select one radio button when not defining the multi variable

### Actual outcome

able to select multiple radio buttons..

### Steps to reproduce

```
                <paper-radio-group id="searchResponseRadioGroup">
                  <template id="domRepeatSearchResponse" is="dom-repeat" items="{{ajaxSearchResponse}}">
                    <paper-radio-button checked={{item.checked}} id="searchResultObject">
                        <div>
                          <span> [[item.name]]</span>
                        </div>
                        <div secondary>
                          <span> [[item.parent.name]] [[item.parent.parent.name]]</span>
                        </div>
                    </paper-radio-button>
                  </template>
                </paper-radio-group>
```

Happens with and without the `checked={{item.checked}}` part and with or without `allow-empty-selection` 

### Browsers Affected
Tested on latest Chrome:
- [ x ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
You need to have a `name` attribute on your `paper-radio-button`s, so that they can be uniquely identifiable. The classic example is:
```
<paper-radio-group selected="small">
  <paper-radio-button name="small">Small</paper-radio-button>
  <paper-radio-button name="medium">Medium</paper-radio-button>
  <paper-radio-button name="large">Large</paper-radio-button>
</paper-radio-group>
```

**Comment by Nachtmerrie** [comment]
My apologies. It even says so in the README
I expected them to work like a paper-menu
